//! Workload classifier — labels an incoming prompt with workload tags
//! drawn from the V107 workload_taxonomy. Drives capability matching in
//! the dispatcher (task #145).
//!
//! Wave 1 of the demand-driven parallel dispatcher. This module is
//! the "what kind of work is this?" leg; the "who can do it?" leg
//! lives in the `fleet_capability_by_host` view; the "fan out + judge"
//! glue lands in subsequent commits.
//!
//! Generated by sophie's qwen3-coder-30b — 2026-05-21.

use reqwest::Client;
use serde_json::json;
use tracing::warn;

const VALID_TAGS: &[&str] = &[
    "chat",
    "code-gen",
    "vision",
    "audio",
    "research",
    "docs",
    "embedding",
    "reranking",
    "training",
    "eval",
    "download",
    "general",
];

pub async fn classify_workload(
    prompt: &str,
    llm_endpoint: &str,
    http: &Client,
) -> Result<Vec<String>, String> {
    let body = json!({
        "model": "default",
        "max_tokens": 64,
        "temperature": 0,
        "messages": [
            {"role": "system", "content": "Reply with only a comma-separated list of tags from: chat, code-gen, vision, audio, research, docs, embedding, reranking, training, eval, download, general"},
            {"role": "user", "content": prompt}
        ]
    });
    let resp = http
        .post(format!("{}/v1/chat/completions", llm_endpoint))
        .json(&body)
        .send()
        .await
        .map_err(|e| format!("http: {e}"))?;
    if !resp.status().is_success() {
        return Err(format!("status {}", resp.status()));
    }
    let v: serde_json::Value = resp.json().await.map_err(|e| format!("json: {e}"))?;
    let content = v["choices"][0]["message"]["content"]
        .as_str()
        .ok_or("no content")?;
    let tags: Vec<String> = content
        .split(',')
        .map(|s| s.trim().to_lowercase())
        .filter(|t| VALID_TAGS.contains(&t.as_str()))
        .collect();
    if tags.is_empty() {
        warn!("classifier returned no valid tags; falling back to general");
        Ok(vec!["general".into()])
    } else {
        Ok(tags)
    }
}
