//! OS-portable liveness probe for running tasks. Captures cpu%, RSS,
//! pid_state via `ps` (works on macOS + Linux). Inserts one row into
//! `task_liveness_probes` per probe call.
//!
//! Generated by sophie's qwen3-coder-30b — 2026-05-21.
//!
//! NOTE: the column name `disk_write_bytes` here is a misnomer — it
//! actually holds RSS in KB (the schema accepts BIGINT). Leaving the
//! name as-is matches sophie's output; a follow-up task should either
//! rename the column or add proper disk-I/O measurement on Linux via
//! /proc/PID/io. Tracked as #157 (progress signal adapters).

use sqlx::PgPool;
use tracing::warn;
use uuid::Uuid;

pub async fn probe_task(pool: &PgPool, task_id: Uuid, pid: i32) -> Result<(), sqlx::Error> {
    let output = tokio::process::Command::new("ps")
        .args(["-o", "pid=,%cpu=,rss=,state=", "-p", &pid.to_string()])
        .output()
        .await;
    let (cpu_pct, rss_kb, pid_state) = match output {
        Ok(out) if out.status.success() => {
            let s = String::from_utf8_lossy(&out.stdout);
            let line = s.trim();
            let mut parts = line.split_whitespace();
            let _pid = parts.next();
            let cpu: Option<f32> = parts.next().and_then(|t| t.parse().ok());
            let rss: Option<i64> = parts.next().and_then(|t| t.parse().ok());
            let state: Option<String> = parts
                .next()
                .map(|t| t.chars().next().unwrap_or('?').to_string());
            (cpu, rss, state)
        }
        _ => {
            warn!("ps failed for pid {} — assuming dead", pid);
            (None, None, Some("Z".to_string()))
        }
    };
    sqlx::query(
        "INSERT INTO task_liveness_probes (task_id, cpu_pct, disk_write_bytes, pid_state)
         VALUES ($1, $2, $3, $4)",
    )
    .bind(task_id)
    .bind(cpu_pct)
    .bind(rss_kb)
    .bind(pid_state.as_deref())
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn probe_all_running(pool: &PgPool, this_host: &str) -> Result<usize, sqlx::Error> {
    let rows: Vec<(Uuid, Option<i32>)> = sqlx::query_as(
        "SELECT t.id, (t.result->>'pid')::int
           FROM fleet_tasks t
           JOIN computers c ON c.id = t.claimed_by_computer_id
          WHERE c.name = $1
            AND t.status = 'running'",
    )
    .bind(this_host)
    .fetch_all(pool)
    .await?;
    let mut count = 0;
    for (task_id, maybe_pid) in rows {
        if let Some(pid) = maybe_pid
            && probe_task(pool, task_id, pid).await.is_ok()
        {
            count += 1;
        }
    }
    Ok(count)
}
