//! Task liveness watchdog — reads the latest `task_liveness_probes` row
//! for a task and classifies it into Alive / Slow / Stuck / Dead.
//!
//! Used by the daemon liveness tick (#160) to decide whether to retry,
//! notify, or hard-cancel a task.
//!
//! Generated by sophie's qwen3-coder-30b — 2026-05-21.

use chrono::{DateTime, Utc};
use sqlx::PgPool;
use uuid::Uuid;

type LivenessProbeRow = (Option<f32>, Option<String>, Option<DateTime<Utc>>);

#[derive(Debug, Clone, PartialEq)]
pub enum TaskLiveness {
    Alive,
    Slow,
    Stuck,
    Dead,
}

pub async fn evaluate_task(
    pool: &PgPool,
    task_id: Uuid,
    max_idle_secs: i64,
) -> Result<TaskLiveness, sqlx::Error> {
    let row: Option<LivenessProbeRow> = sqlx::query_as(
        "SELECT cpu_pct, pid_state, probed_at FROM task_liveness_probes WHERE task_id = $1 ORDER BY probed_at DESC LIMIT 1"
    ).bind(task_id).fetch_optional(pool).await?;
    let Some((cpu_pct, pid_state, probed_at)) = row else {
        return Ok(TaskLiveness::Alive);
    };
    if matches!(pid_state.as_deref(), Some("Z") | Some("z")) {
        return Ok(TaskLiveness::Dead);
    }
    let cpu = cpu_pct.unwrap_or(0.0);
    let probe_age = probed_at
        .map(|t| (Utc::now() - t).num_seconds())
        .unwrap_or(0);
    if cpu > 5.0 {
        return Ok(TaskLiveness::Alive);
    }
    if probe_age > max_idle_secs {
        return Ok(TaskLiveness::Stuck);
    }
    if cpu < 1.0 {
        return Ok(TaskLiveness::Slow);
    }
    Ok(TaskLiveness::Alive)
}
