CREATE TABLE model_metrics (
    recorded_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    node                 TEXT NOT NULL,
    port                 INTEGER NOT NULL CHECK (port BETWEEN 1 AND 65535),
    model                TEXT NOT NULL,
    batch_occupancy      DOUBLE PRECISION,
    kv_cache_util        DOUBLE PRECISION,
    queue_depth          BIGINT,
    prompt_tokens_total  BIGINT,
    output_tokens_total  BIGINT
) PARTITION BY RANGE (recorded_at);

CREATE INDEX model_metrics_node_model_time_idx
    ON model_metrics (node, model, recorded_at DESC);

CREATE TABLE model_metrics_1m (
    bucket_start          TIMESTAMPTZ NOT NULL,
    node                  TEXT NOT NULL,
    port                  INTEGER NOT NULL CHECK (port BETWEEN 1 AND 65535),
    model                 TEXT NOT NULL,
    sample_count          BIGINT NOT NULL,
    batch_occupancy_avg   DOUBLE PRECISION,
    batch_occupancy_max   DOUBLE PRECISION,
    kv_cache_util_avg     DOUBLE PRECISION,
    kv_cache_util_max     DOUBLE PRECISION,
    queue_depth_avg       DOUBLE PRECISION,
    queue_depth_max       BIGINT,
    prompt_tokens         BIGINT NOT NULL DEFAULT 0,
    output_tokens         BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (bucket_start, node, port, model)
) PARTITION BY RANGE (bucket_start);

CREATE INDEX model_metrics_1m_node_model_time_idx
    ON model_metrics_1m (node, model, bucket_start DESC);

CREATE TABLE hourly_metrics (
    bucket_start          TIMESTAMPTZ NOT NULL,
    node                  TEXT NOT NULL,
    port                  INTEGER NOT NULL CHECK (port BETWEEN 1 AND 65535),
    model                 TEXT NOT NULL,
    sample_count          BIGINT NOT NULL,
    batch_occupancy_avg   DOUBLE PRECISION,
    batch_occupancy_max   DOUBLE PRECISION,
    kv_cache_util_avg     DOUBLE PRECISION,
    kv_cache_util_max     DOUBLE PRECISION,
    queue_depth_avg       DOUBLE PRECISION,
    queue_depth_max       BIGINT,
    prompt_tokens         BIGINT NOT NULL DEFAULT 0,
    output_tokens         BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (bucket_start, node, port, model)
) PARTITION BY RANGE (bucket_start);

CREATE INDEX hourly_metrics_node_model_time_idx
    ON hourly_metrics (node, model, bucket_start DESC);

CREATE TABLE model_error_events (
    occurred_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    node         TEXT NOT NULL,
    port         INTEGER CHECK (port BETWEEN 1 AND 65535),
    model        TEXT,
    error_class  TEXT NOT NULL,
    message      TEXT NOT NULL,
    details      JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (occurred_at, id)
) PARTITION BY RANGE (occurred_at);

CREATE INDEX model_error_events_class_time_idx
    ON model_error_events (error_class, occurred_at DESC);
CREATE INDEX model_error_events_node_model_time_idx
    ON model_error_events (node, model, occurred_at DESC);

-- Creates the UTC calendar-month partitions containing p_at. It is safe for
-- multiple maintainers to call this concurrently and uses no session state,
-- which keeps ingestion compatible with PgCat transaction pooling.
CREATE OR REPLACE FUNCTION create_model_metrics_partitions(p_at TIMESTAMPTZ DEFAULT NOW())
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    month_start TIMESTAMPTZ := date_trunc('month', p_at AT TIME ZONE 'UTC') AT TIME ZONE 'UTC';
    month_end   TIMESTAMPTZ := month_start + INTERVAL '1 month';
    parent_name TEXT;
BEGIN
    PERFORM pg_advisory_xact_lock(hashtext('create_model_metrics_partitions'),
                                  EXTRACT(YEAR FROM month_start)::INTEGER * 100
                                  + EXTRACT(MONTH FROM month_start)::INTEGER);

    FOREACH parent_name IN ARRAY ARRAY[
        'model_metrics', 'model_metrics_1m', 'hourly_metrics', 'model_error_events'
    ]
    LOOP
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.%I FOR VALUES FROM (%L) TO (%L)',
            parent_name || '_p' || to_char(month_start AT TIME ZONE 'UTC', 'YYYYMM'),
            parent_name,
            month_start,
            month_end
        );
    END LOOP;
END;
$$;

-- Retention is partition-granular: raw samples and errors retain at least 7
-- days, while minute/hour rollups retain at least 30 days. With monthly
-- partitions, a partition is dropped only after its entire month is expired.
CREATE OR REPLACE FUNCTION drop_old_model_metrics_partitions(
    raw_retention INTERVAL DEFAULT INTERVAL '7 days',
    rollup_retention INTERVAL DEFAULT INTERVAL '30 days'
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    child RECORD;
    partition_month DATE;
    retention INTERVAL;
    dropped INTEGER := 0;
BEGIN
    IF raw_retention <= INTERVAL '0' OR rollup_retention <= INTERVAL '0' THEN
        RAISE EXCEPTION 'retention intervals must be positive';
    END IF;

    FOR child IN
        SELECT parent.relname AS parent_name, child.relname AS child_name
          FROM pg_inherits
          JOIN pg_class parent ON parent.oid = inhparent
          JOIN pg_namespace parent_ns ON parent_ns.oid = parent.relnamespace
          JOIN pg_class child ON child.oid = inhrelid
          JOIN pg_namespace child_ns ON child_ns.oid = child.relnamespace
         WHERE parent_ns.nspname = 'public'
           AND child_ns.nspname = 'public'
           AND parent.relname IN (
               'model_metrics', 'model_metrics_1m', 'hourly_metrics', 'model_error_events'
           )
    LOOP
        IF child.child_name !~ ('^' || child.parent_name || '_p[0-9]{6}$') THEN
            CONTINUE;
        END IF;

        partition_month := to_date(right(child.child_name, 6), 'YYYYMM');
        retention := CASE
            WHEN child.parent_name IN ('model_metrics', 'model_error_events') THEN raw_retention
            ELSE rollup_retention
        END;

        IF (partition_month + INTERVAL '1 month') <= NOW() - retention THEN
            EXECUTE format('DROP TABLE public.%I', child.child_name);
            dropped := dropped + 1;
        END IF;
    END LOOP;

    RETURN dropped;
END;
$$;

SELECT create_model_metrics_partitions(NOW());
SELECT create_model_metrics_partitions(NOW() + INTERVAL '1 month');
